userName = input("What is your name?")
age = input("How old are you?")
location = input("Where are you live?")
print(("this is") + userName)
print(("It is") + age)
print(("He/she live in") + location)